### ISSUE TITLE
npm install fails with iojs v2.0.0

### ISSUE THREAD

**Issue by florianschmidt1994** [Project-OSRM/node-osrm#100]
Installing with ```npm install osrm``` fails with io.js in version 2.0.0. Works fine with node version 0.12.0. I attached my output, hope this helps:

```
npm WARN engine osrm@4.6.1: wanted: {"node":"0.10.x"} (current: {"node":"2.0.0","npm":"2.9.0"})
-
> osrm@4.6.1 install /Users/florianschmidt/Development/roadstar/mapmatching/node_modules/osrm
> node-pre-gyp install --fallback-to-build

Package libosrm was not found in the pkg-config search path.
Perhaps you should add the directory containing `libosrm.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libosrm' found
gyp: Call to 'pkg-config libosrm --libs --static' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/florianschmidt/.nvm/versions/io.js/v2.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1009:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/Users/florianschmidt/.nvm/versions/io.js/v2.0.0/bin/iojs" "/Users/florianschmidt/.nvm/versions/io.js/v2.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/florianschmidt/Development/roadstar/mapmatching/node_modules/osrm/lib/binding/osrm.node" "--module_name=osrm" "--module_path=/Users/florianschmidt/Development/roadstar/mapmatching/node_modules/osrm/lib/binding"
gyp ERR! cwd /Users/florianschmidt/Development/roadstar/mapmatching/node_modules/osrm
gyp ERR! node -v v2.0.0
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/florianschmidt/.nvm/versions/io.js/v2.0.0/bin/iojs /Users/florianschmidt/.nvm/versions/io.js/v2.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/florianschmidt/Development/roadstar/mapmatching/node_modules/osrm/lib/binding/osrm.node --module_name=osrm --module_path=/Users/florianschmidt/Development/roadstar/mapmatching/node_modules/osrm/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/florianschmidt/Development/roadstar/mapmatching/node_modules/osrm/node_modules/node-pre-gyp/lib/util/compile.js:73:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:169:7)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:953:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1020:5)
node-pre-gyp ERR! System Darwin 14.3.0
node-pre-gyp ERR! command "/Users/florianschmidt/.nvm/versions/io.js/v2.0.0/bin/iojs" "/Users/florianschmidt/Development/roadstar/mapmatching/node_modules/osrm/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/florianschmidt/Development/roadstar/mapmatching/node_modules/osrm
node-pre-gyp ERR! node -v v2.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.4
node-pre-gyp ERR! not ok
Failed to execute '/Users/florianschmidt/.nvm/versions/io.js/v2.0.0/bin/iojs /Users/florianschmidt/.nvm/versions/io.js/v2.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/florianschmidt/Development/roadstar/mapmatching/node_modules/osrm/lib/binding/osrm.node --module_name=osrm --module_path=/Users/florianschmidt/Development/roadstar/mapmatching/node_modules/osrm/lib/binding' (1)
npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/florianschmidt/.nvm/versions/io.js/v2.0.0/bin/iojs" "/Users/florianschmidt/.nvm/versions/io.js/v2.0.0/bin/npm" "install" "osrm"
npm ERR! node v2.0.0
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE

npm ERR! osrm@4.6.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the osrm@4.6.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the osrm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls osrm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/florianschmidt/Development/roadstar/mapmatching/npm-debug.log
```

**Comment by springmeyer** [comment]
Hi @florianschmidt1994 - this failure is expected. We only provide binaries of node-osrm for Node v0.10.x and node v0.12.x currently. The io.js releases are moving too fast in my opinion to make to easy to track them. Happy to reconsider this if io.js support is important to you, but for now that is why binaries do not exist.

So, If binaries are not available then the build falls back to a source compile against osrm-backend. In your case that is failing because you don't have `osrm-backend` installed, or at least you don't have the `libosrm.pc` installed on PKG_CONFIG_PATH so that `pkg-config --libs libosrm` can find your osrm-backend install.

Let me know if it is okay for you to stick to node v0.12.x. If not I can either start building io.js binaries or help you get a source compile going easily.

**Comment by florianschmidt1994** [comment]
Hi @springmeyer - Using node v0.12.0 is just fine for now. I will maybe try to do a source compile some time again, and I will let you know whether I run into any other issues there. Thanks for your support anyway!

**Comment by wwymak** [comment]
Um, I ran into a similar issue with Node v.4, but I've done a source build, but it is throwing error:

```npm install --build-from-source
npm WARN package.json osrm@4.8.1 No license field.
osrm@4.8.1 install /Users/wwymak/Desktop/code_experiments/london_mapping/node_modules/node-osrm
 node-pre-gyp install --fallback-to-build
CXX(target) Release/obj.target/osrm/src/node_osrm.o
In file included from ../src/node_osrm.cpp:1:
In file included from ../src/json_v8_renderer.hpp:37:
../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
../node_modules/nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in
      namespace 'node'
    , node::smalloc::FreeCallback callback
    ../node_modules/nan/nan.h:672:12: error: no matching function for call to
      'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
/Users/wwymak/.node-gyp/4.1.1/include/node/node_buffer.h:31:40: note:
      candidate function not viable: no known conversion from 'uint32_t'
      (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
/Users/wwymak/.node-gyp/4.1.1/include/node/node_buffer.h:43:40: note:
      candidate function not viable: 2nd argument ('const char *') would lose
      const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,

/Users/wwymak/.node-gyp/4.1.1/include/node/node_buffer.h:28:40: note:
      candidate function not viable: requires 2 arguments, but 3 were
      provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size...
/Users/wwymak/.node-gyp/4.1.1/include/node/node_buffer.h:36:40: note:
      candidate function not viable: requires 5 arguments, but 3 were
      provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
   In file included from ../src/node_osrm.cpp:1:
In file included from ../src/json_v8_renderer.hpp:37:
../node_modules/nan/nan.h:676:12: error: no viable conversion from
      'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
/Users/wwymak/.node-gyp/4.1.1/include/node/v8.h:210:7: note: candidate
      constructor (the implicit copy constructor) not viable: no known
      conversion from 'v8::MaybeLocal<v8::Object>' to 'const
      v8::Local<v8::Object> &' for 1st argument
class Local {
/Users/wwymak/.node-gyp/4.1.1/include/node/v8.h:210:7: note: candidate
      constructor (the implicit move constructor) not viable: no known
      conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>
      &&' for 1st argument
class Local {
/Users/wwymak/.node-gyp/4.1.1/include/node/v8.h:214:13: note: candidate
      template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
/Users/wwymak/.node-gyp/4.1.1/include/node/v8.h:326:13: note: candidate
      template ignored: could not match 'S *' against
      'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
In file included from ../src/node_osrm.cpp:1:
In file included from ../src/json_v8_renderer.hpp:37:
../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace
      'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
../src/node_osrm.cpp:632:15: warning: 'FatalException' is deprecated: Use
      FatalException(isolate, ...) [-Wdeprecated-declarations]
        node::FatalException(try_catch);
/Users/wwymak/.node-gyp/4.1.1/include/node/node.h:283:29: note:
      'FatalException' has been explicitly marked deprecated here
                inline void FatalException(const v8::TryCatch& try_catch) {
/Users/wwymak/.node-gyp/4.1.1/include/node/node.h:66:42: note: expanded from
      macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
In file included from ../src/node_osrm.cpp:1:
In file included from ../src/json_v8_renderer.hpp:37:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/wwymak/.node-gyp/4.1.1/include/node/node.h:42:
/Users/wwymak/.node-gyp/4.1.1/include/node/v8.h:221:5: error: assigning to
      'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
/Users/wwymak/.node-gyp/4.1.1/include/node/v8.h:180:37: note: expanded from
      macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);    
../node_modules/nan/nan.h:414:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested
      here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
  define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
In file included from ../src/node_osrm.cpp:1:
In file included from ../src/json_v8_renderer.hpp:37:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/wwymak/.node-gyp/4.1.1/include/node/node.h:42:
/Users/wwymak/.node-gyp/4.1.1/include/node/v8.h:221:5: error: assigning to
      'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
/Users/wwymak/.node-gyp/4.1.1/include/node/v8.h:180:37: note: expanded from
      macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);    
../node_modules/nan/nan.h:424:12: note: in instantiation of function template
      specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested
      here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
 define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
In file included from ../src/node_osrm.cpp:1:
In file included from ../src/json_v8_renderer.hpp:37:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/wwymak/.node-gyp/4.1.1/include/node/node.h:42:
/Users/wwymak/.node-gyp/4.1.1/include/node/v8.h:221:5: error: assigning to
      'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
/Users/wwymak/.node-gyp/4.1.1/include/node/v8.h:180:37: note: expanded from
      macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);     
../node_modules/nan/nan.h:1514:12: note: in instantiation of function
      template specialization 'v8::Local<v8::Function>::Local<v8::Value>'
      requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
 define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
In file included from ../src/node_osrm.cpp:1:
In file included from ../src/json_v8_renderer.hpp:37:
In file included from ../node_modules/nan/nan.h:24:
In file included from /Users/wwymak/.node-gyp/4.1.1/include/node/node.h:42:
/Users/wwymak/.node-gyp/4.1.1/include/node/v8.h:221:5: error: assigning to
      'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
/Users/wwymak/.node-gyp/4.1.1/include/node/v8.h:180:37: note: expanded from
      macro 'TYPE_CHECK'
    (static_cast<T* volatile*>(0)) = static_cast<S*>(0);   
../node_modules/nan/nan.h:1632:12: note: in instantiation of function
      template specialization 'v8::Local<v8::Object>::Local<v8::Value>'
      requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
 define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
1 warning and 9 errors generated.
make: *** [Release/obj.target/osrm/src/node_osrm.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/wwymak/Desktop/code_experiments/london_mapping/node_modules/node-osrm/lib/binding/osrm.node" "--module_name=osrm" "--module_path=/Users/wwymak/Desktop/code_experiments/london_mapping/node_modules/node-osrm/lib/binding"
gyp ERR! cwd /Users/wwymak/Desktop/code_experiments/london_mapping/node_modules/node-osrm
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/wwymak/Desktop/code_experiments/london_mapping/node_modules/node-osrm/lib/binding/osrm.node --module_name=osrm --module_path=/Users/wwymak/Desktop/code_experiments/london_mapping/node_modules/node-osrm/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/wwymak/Desktop/code_experiments/london_mapping/node_modules/node-osrm/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 15.2.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/wwymak/Desktop/code_experiments/london_mapping/node_modules/node-osrm/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/wwymak/Desktop/code_experiments/london_mapping/node_modules/node-osrm
node-pre-gyp ERR! node -v v4.1.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.18
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/wwymak/Desktop/code_experiments/london_mapping/node_modules/node-osrm/lib/binding/osrm.node --module_name=osrm --module_path=/Users/wwymak/Desktop/code_experiments/london_mapping/node_modules/node-osrm/lib/binding' (1)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--build-from-source"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! osrm@4.8.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the osrm@4.8.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the osrm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls osrm
npm ERR! There is likely additional logging output above.```

Any tips on how to get this to work would be great. Thanks!

**Comment by springmeyer** [comment]
@wwymak node v4 is not supported yet, so this error is expected. Keep an eye on https://github.com/Project-OSRM/node-osrm/pull/125 which is needed for node v4/5 support.

**Comment by ronhippler** [comment]
should be closed?

**Comment by TheMarex** [comment]
Yes node v4/v5 are now supported.

**Comment by ambodi** [comment]
but I am getting the same error on node v6.3.1 😞

**Comment by daniel-j-h** [comment]
https://github.com/Project-OSRM/node-osrm#depends
> Node.js v4.x

**Comment by ambodi** [comment]
Oh man! You guys are It's not like one major behind, but like 2!

Any plans for V6 support?

**Comment by daniel-j-h** [comment]
We care about stability in production environments. v4 is the current LTS version:

https://github.com/nodejs/LTS

v6 will only become the next LTS version starting October (in a month).

But as an open source project we're of course accepting patches already before that.
