### ISSUE TITLE
Build fails on "npm install osrm" looking for 'libosrm_config.hpp' But the same file does not exist in osrm-backend build.

### ISSUE THREAD

**Issue by mkkhedawat** [Project-OSRM/node-osrm#163]
```
mkh6kor/.../map$ npm install osrm

> osrm@4.7.1 install /home/mkh6kor/.../map/node_modules/osrm
> node-pre-gyp install --fallback-to-build

make: Entering directory `/home/mkh6kor/.../map/node_modules/osrm/build'
  CXX(target) Release/obj.target/osrm/src/node_osrm.o
../src/node_osrm.cpp:8:35: fatal error: osrm/libosrm_config.hpp: No such file or directory
 #include <osrm/libosrm_config.hpp>
                                   ^
compilation terminated.
make: *** [Release/obj.target/osrm/src/node_osrm.o] Error 1
make: Leaving directory `/home/mkh6kor/.../map/node_modules/osrm/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-62-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/mkh6kor/.../map/node_modules/osrm/lib/binding/osrm.node" "--module_name=osrm" "--module_path=/home/mkh6kor/.../map/node_modules/osrm/lib/binding"
gyp ERR! cwd /home/mkh6kor/.../map/node_modules/osrm
gyp ERR! node -v v5.7.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/mkh6kor/.../map/node_modules/osrm/lib/binding/osrm.node --module_name=osrm --module_path=/home/mkh6kor/.../map/node_modules/osrm/lib/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/mkh6kor/.../map/node_modules/osrm/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:100:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 3.16.0-62-generic
node-pre-gyp ERR! command "/usr/bin/nodejs" "/home/mkh6kor/.../map/node_modules/osrm/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/mkh6kor/.../map/node_modules/osrm
node-pre-gyp ERR! node -v v5.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.9
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/nodejs /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/mkh6kor/.../map/node_modules/osrm/lib/binding/osrm.node --module_name=osrm --module_path=/home/mkh6kor/.../map/node_modules/osrm/lib/binding' (1)
npm WARN install:osrm@4.7.1 osrm@4.7.1 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:osrm@4.7.1 Exit status 1
npm WARN mapService@0.0.1 No repository field.
npm WARN mapService@0.0.1 No license field.
mkh6kor@server:~/.../map$ pkg-config libosrm --variable=prefix
/usr/local
mkh6kor@server:~/.../map$ g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

mkh6kor@server:~/.../map$ node --version
v5.7.0
mkh6kor@server:~/.../map$ 

```

Am I missing something ?

**Comment by springmeyer** [comment]
The problem is likely that the osrm-backend version you have installed is not compatible. I recommend building osrm-backend `develop` branch. And then cloning the `develop` branch of node-osrm. Then follow the instructions at https://github.com/Project-OSRM/node-osrm#using-an-existing-local-osrm-backend to build one against the other. Please open a new ticket if you are still having trouble.

**Comment by cvvergara** [comment]
@springmeyer 
There is no develop branch

**Comment by cvvergara** [comment]
forgot to mention where: on osrm-backend

**Comment by springmeyer** [comment]
@cvvergara right, there is no develop branch now. Node-osrm targets the version of osrm-backend listed here: https://github.com/Project-OSRM/node-osrm/blob/master/package.json#L8. If you are having issues installing, please open a new issue.
