### ISSUE TITLE
Main node thread blocked when worker thread gets stuck

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/node-osrm#166]
We attempted a cross-USA route with alternatives enabled with a core factor of 0.8.  This lead to a *very* long request time.

In the meantime, the Node instance hosting `node-osrm` locked up and stopped accepting more requests.  It appeared that the main thread was blocked.  The system was built without debugging symbols, so here's all I managed to extract:

```
(gdb) info threads
  Id   Target Id         Frame
  14   Thread 0x7fd8e1aee700 (LWP 3220) "SignalSender" sem_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_wait.S:85
  13   Thread 0x7fd8aec90700 (LWP 3228) "node" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  12   Thread 0x7fd8ae48f700 (LWP 3229) "node" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  11   Thread 0x7fd8adc8e700 (LWP 3230) "node" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  10   Thread 0x7fd8ad48d700 (LWP 3231) "node" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  9    Thread 0x7fd8acc8c700 (LWP 3232) "node" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  8    Thread 0x7fd8ac48b700 (LWP 3233) "node" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  7    Thread 0x7fd8abc8a700 (LWP 3234) "node" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  6    Thread 0x7fd8ab489700 (LWP 3235) "node" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  5    Thread 0x7fd8aac88700 (LWP 3236) "node" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  4    Thread 0x7fd8aa487700 (LWP 3237) "node" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  3    Thread 0x7fd8a9c86700 (LWP 3238) "node" 0x00007fd8e0483dde in osrm::engine::SearchEngineData::InitializeOrClearSecondThreadLocalStorage(unsigned int) () from node_modules/osrm/lib/binding/osrm.node
  2    Thread 0x7fd8a9485700 (LWP 3239) "node" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
* 1    Thread 0x7fd8e1af0780 (LWP 3219) "node" syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
```

Backtrace on the main thread:
```
(gdb) bt
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x0000000000a189ba in uv__epoll_wait (epfd=-906766032, events=0x400, nevents=-1, timeout=78373)
    at ../deps/uv/src/unix/linux-syscalls.c:283
#2  0x0000000000a177e6 in uv__io_poll (loop=0xed5b00 <default_loop_struct>, timeout=4999) at ../deps/uv/src/unix/linux-core.c:211
#3  0x0000000000a0b6d5 in uv_run (loop=0xed5b00 <default_loop_struct>, mode=UV_RUN_DEFAULT) at ../deps/uv/src/unix/core.c:317
#4  0x00000000009b2d0d in node::Start(int, char**) ()
#5  0x00007fd8e06ecec5 in __libc_start_main (main=0x9c4180 <main>, argc=2, argv=0x7ffdc9f40ba8, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7ffdc9f40b98) at libc-start.c:287
#6  0x00000000005a6929 in _start ()
```

Backtrace on the one active worker thread that appeared to be stuck:
```
(gdb) thread apply 3 bt
Thread 3 (Thread 0x7fd8a9c86700 (LWP 3238)):
#0  0x00007fd8e0483dde in osrm::engine::SearchEngineData::InitializeOrClearSecondThreadLocalStorage(unsigned int) ()
   from node_modules/osrm/lib/binding/osrm.node
#1  0x00007fd8e0472e74 in osrm::engine::routing_algorithms::AlternativeRouting<osrm::engine::datafacade::BaseDataFacade>::ComputeLengthAndSharingOfViaPath(unsigned int, int*, int*, std::vector<unsigned int, std::allocator<unsigned int> > const&, int) ()
   from node_modules/osrm/lib/binding/osrm.node
#2  0x00007fd8e04774d7 in osrm::engine::routing_algorithms::AlternativeRouting<osrm::engine::datafacade::BaseDataFacade>::operator()(osrm::engine::PhantomNodes const&, osrm::engine::InternalRouteResult&) () from node_modules/osrm/lib/binding/osrm.node
#3  0x00007fd8e047b8e8 in osrm::engine::plugins::ViaRoutePlugin::HandleRequest(osrm::engine::api::RouteParameters const&, osrm::util::json::Object&) () from node_modules/osrm/lib/binding/osrm.node
#4  0x00007fd8e043428b in osrm::engine::Engine::Route(osrm::engine::api::RouteParameters const&, osrm::util::json::Object&) ()
   from node_modules/osrm/lib/binding/osrm.node
#5  0x00007fd8e040804d in node_osrm::Engine::AsyncRunRoute(uv_work_s*) () from node_modules/osrm/lib/binding/osrm.node
#6  0x0000000000a14564 in worker (arg=<optimized out>) at ../deps/uv/src/unix/threadpool.c:74
#7  0x0000000000a0a202 in uv__thread_start (ctx_v=<optimized out>) at ../deps/uv/src/uv-common.c:323
#8  0x00007fd8e0a98182 in start_thread (arg=0x7fd8a9c86700) at pthread_create.c:312
#9  0x00007fd8e07c547d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

The code for `InitializeOrClearSecondThreadLocalStorage` looks pretty innocent, so I suspect it has been inlined and the problem is deeper within one of its callees.

It is not clear to me why the `node` main thread has stopped responding, unless something in `InitializeOrClearSecondThreadLocalStorage` has caused a deadlock.

At the time this backtrace was taken, there was 1 CPU core pegged at 100% CPU.  It was not obvious which thread was doing the work, I ran `bt` a few times and nothing seemed to change.

**Comment by TheMarex** [comment]
Maybe related to https://github.com/Project-OSRM/node-osrm/issues/109

**Comment by springmeyer** [comment]
libuv uses thread local storage since https://github.com/joyent/libuv/issues/904. I wonder if there is some clobbering going on. Did OSRM always use thread local storage or is this a new thing?

**Comment by TheMarex** [comment]
We have been always using thread local storage as long as I can remember. We need it for multiple things, bust most importantly the binary heaps that are used in each search are thread local.

**Comment by springmeyer** [comment]
Quite a different issue (since this only happened at exit), but linking this nonetheless for possible clues of what clobbering can lead to: https://trac.osgeo.org/gdal/ticket/5509

**Comment by springmeyer** [comment]
@danpat - can you confirm which node version this was seen with?

**Comment by danpat** [comment]
```
$ node --version
v0.10.42
```

**Comment by TheMarex** [comment]
Is this still an issue?

**Comment by TheMarex** [comment]
Closing because we dropped 0.10 support.
