### ISSUE TITLE
make test fails

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/node-osrm#207]
following the documentation, i'm trying to run 'make test' inside the node-osrm module folder, but it fails. i've installed latest 5.2.2. i'm on ubuntu 16, with preinstalled node 4.2.6.

```shell
root@routes3:~/node_modules/osrm# make test
*** Using osrm-datastore from ./lib/binding/osrm-datastore ***
make[1]: Entering directory '/root/node_modules/osrm/test/data'
wget https://s3.amazonaws.com/mapbox/node-osrm/testing/berlin-latest.osm.pbf -O berlin-latest.osm.pbf
--2016-06-16 07:09:37--  https://s3.amazonaws.com/mapbox/node-osrm/testing/berlin-latest.osm.pbf
Resolving s3.amazonaws.com (s3.amazonaws.com)... 54.231.50.20
Connecting to s3.amazonaws.com (s3.amazonaws.com)|54.231.50.20|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 47183031 (45M) [binary/octet-stream]
Saving to: 'berlin-latest.osm.pbf'

berlin-latest.osm.pbf                   100%[==============================================================================>]  45.00M  2.48MB/s    in 4m 44s  

2016-06-16 07:14:22 (162 KB/s) - 'berlin-latest.osm.pbf' saved [47183031/47183031]

mkdir -p lib
wget https://raw.githubusercontent.com/Project-OSRM/osrm-backend/v5.2.2/profiles/lib/access.lua -O lib/access.lua
--2016-06-16 07:14:22--  https://raw.githubusercontent.com/Project-OSRM/osrm-backend/v5.2.2/profiles/lib/access.lua
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.31.17.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.31.17.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 309 [text/plain]
Saving to: 'lib/access.lua'

lib/access.lua                          100%[==============================================================================>]     309  --.-KB/s    in 0s      

2016-06-16 07:14:22 (43.4 MB/s) - 'lib/access.lua' saved [309/309]

mkdir -p lib
wget https://raw.githubusercontent.com/Project-OSRM/osrm-backend/v5.2.2/profiles/lib/destination.lua -O lib/destination.lua
--2016-06-16 07:14:22--  https://raw.githubusercontent.com/Project-OSRM/osrm-backend/v5.2.2/profiles/lib/destination.lua
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.31.17.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.31.17.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 630 [text/plain]
Saving to: 'lib/destination.lua'

lib/destination.lua                     100%[==============================================================================>]     630  --.-KB/s    in 0s      

2016-06-16 07:14:22 (125 MB/s) - 'lib/destination.lua' saved [630/630]

wget https://raw.githubusercontent.com/Project-OSRM/osrm-backend/v5.2.2/profiles/car.lua -O car.lua
--2016-06-16 07:14:22--  https://raw.githubusercontent.com/Project-OSRM/osrm-backend/v5.2.2/profiles/car.lua
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.31.17.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.31.17.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15538 (15K) [text/plain]
Saving to: 'car.lua'

car.lua                                 100%[==============================================================================>]  15.17K  --.-KB/s    in 0.01s   

2016-06-16 07:14:23 (1.19 MB/s) - 'car.lua' saved [15538/15538]

Verifiyng data file integrity...
md5sum -c data.md5sum
lib/access.lua: OK
lib/destination.lua: OK
car.lua: OK
berlin-latest.osm.pbf: OK
*** Using osrm-extract from ../../lib/binding/osrm-extract ***
Running osrm-extract...
[info] Using script car.lua
[info] Input file: berlin-latest.osm.pbf
[info] Profile: car.lua
[info] Threads: 1
[STXXL-MSG] STXXL v1.4.1 (prerelease/Release)
[STXXL-ERRMSG] Warning: no config file found.
[STXXL-ERRMSG] Using default disk configuration.
[STXXL-MSG] Disk '/var/tmp/stxxl' is allocated, space: 1000 MiB, I/O implementation: syscall autogrow delete_on_exit queue=0 devid=0
[info] Parsing in progress..
[info] input file generated by Osmium (http://wiki.openstreetmap.org/wiki/Osmium)
[info] timestamp: 2015-12-15T20:13:01Z
[info] Found 3 exceptions to turn restrictions:
[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parsing finished after 55.5649 seconds
[info] Raw input contains 4150946 nodes, 630090 ways, and 8888 relations, and 0 unknown entities
[extractor] Sorting used nodes        ... ok, after 2.14492s
[extractor] Erasing duplicate nodes   ... ok, after 0.126106s
[extractor] Sorting all nodes         ... ok, after 38.7904s
[extractor] Building node id map      ... ok, after 11.5783s
[extractor] setting number of nodes   ... ok
[extractor] Confirming/Writing used nodes     ... ok, after 14.7636s
[info] Processed 187657 nodes
[extractor] Sorting edges by start    ... ok, after 6.03987s
[extractor] Setting start coords      ... ok, after 10.6355s
[extractor] Sorting edges by target   ... ok, after 6.95789s
[extractor] Computing edge weights    ... ok, after 23.2691s
[extractor] Sorting edges by renumbered start ... ok, after 6.13133s
[extractor] Writing used edges       ... ok, after 0.016898s
[extractor] setting number of edges   ... ok
[info] Processed 210558 edges
[extractor] Sorting used ways         ... ok, after 0.773273s
[extractor] Sorting 889 restriction. by from... ok, after 0.926702s
[extractor] Fixing restriction starts ... [warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid way: 4611694
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid way: 27166348
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid way: 46895534
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid way: 137728450
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid way: 221387389
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid node: 3738865824
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid way: 314310859
[warn] Restriction references invalid way: 314310860
[warn] Restriction references invalid way: 329733345
[warn] Restriction references invalid node: 4294967295
[warn] Restriction references invalid way: 344108415
[warn] Restriction references invalid node: 4294967295
ok, after 0.125516s
[extractor] Sorting restrictions. by to  ... ok, after 1.12774s
[extractor] Fixing restriction ends   ... ok, after 0.163502s
[info] usable restrictions: 832
[extractor] writing street name index ... ok, after 0.001538s
[info] extraction finished after 180.427s
[info] Generating edge-expanded graph representation
[info]  - 832 restrictions.
[info] Importing n = 187657 nodes 
[info]  - 906 bollard nodes, 4173 traffic lights
[info]  and 210558 edges 
[info] Graph loaded ok and has 210558 edges
. 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Node compression ratio: 0.380652
[info] Edge compression ratio: 0.447917
. 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Generated 210521 nodes in edge-expanded graph
[info] generating edge-expanded edges
. 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Created 42 entry classes and 2392 Bearing Classes
[info] Generated 210521 edge based nodes
[info] Node-based graph contains 169793 edges
[info] Edge-expanded graph ...
[info]   contains 327078 edges
[info]   skips 0 turns, defined by 829 restrictions
[info]   skips 0 U turns
[info]   skips 0 turns over barriers
[info] Timing statistics for edge-expanded graph:
[info] Renumbering edges: 0.00298s
[info] Generating nodes: 0.062573s
[info] Generating edges: 3.59069s
[info] Writing Intersection Classification Data
[info] ok, after 0.000866s for 187657 Indices into 2392 bearing classes and 42 entry classes
[info] Saving edge-based node weights to file.
[info] Done writing. (0.001868)
[info] building r-tree ...
[info] large component [163]=164084
[info] SCC run took: 0.0187762s
[info] constructing r-tree of 210521 edge elements build on-top of 187657 coordinates
[info] finished r-tree construction in 0.193955 seconds
[info] writing node map ...
[info] [extractor] Writing edge-based-graph edges       ... 
[info] ok, after 0.013533s

[info] Processed 327078 edges
[info] Expansion  : 44845.5 nodes/sec and 40576.5 edges/sec
[info] To prepare the data for routing, run: ./osrm-contract berlin-latest.osrm

[STXXL-ERRMSG] Removing disk file: /var/tmp/stxxl
*** Using osrm-contract from ../../lib/binding/osrm-contract ***
Running osrm-contract...
[info] Input file: berlin-latest.osrm
[info] Threads: 1
[info] Loading edge-expanded graph representation
[info] Opening berlin-latest.osrm.ebg
[info] Reading 327078 edges from the edge based graph
[info] Done reading edges
[info] Reading node weights.
[info] Done reading node weights.
[STXXL-MSG] STXXL v1.4.1 (prerelease/Release)
[STXXL-ERRMSG] Warning: no config file found.
[STXXL-ERRMSG] Using default disk configuration.
[STXXL-MSG] Disk '/var/tmp/stxxl' is allocated, space: 1000 MiB, I/O implementation: syscall autogrow delete_on_exit queue=0 devid=0
[info] merged 655110 edges out of 1308312
[info] contractor finished initalization
initializing elimination PQ ...ok
preprocessing 169793 nodes .... 10% . 20% . 30% . 40% . 50% . 60% . [flush 111555 nodes]  70% . 80% . 90% . 100%
[info] [core] 0 nodes 483202 edges.

[info] Getting edges of minimized graph
. 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
[info] Contraction took 52.3521 sec
[info] Serializing compacted graph of 896735 edges
[info] Building node array
[info] Serializing node array
[info] Writing CRC32: 552107888
[info] Building edge array
[info] Preprocessing : 52.6717 seconds
[info] Contraction: 3243.29 nodes/sec and 17128.9 edges/sec
[info] finished preprocessing
[STXXL-ERRMSG] Removing disk file: /var/tmp/stxxl
make[1]: Leaving directory '/root/node_modules/osrm/test/data'
[info] load names from: "./test/data/berlin-latest.osrm.names"
[info] name offsets size: 1841
[info] allocating shared memory of 22740031 bytes
Copying 11 chars into name data ptr
[info] all data loaded
npm test

> osrm@5.2.2 test /root/node_modules/osrm
> node test/index.js

TAP version 13
# constructor: throws if new keyword is not used
ok 1 should throw
# constructor: uses defaults with no parameter
/root/node_modules/osrm/test/index.js:13
    var osrm = new OSRM();
               ^

TypeError: No shared memory blocks found, have you forgotten to run osrm-datastore?
    at TypeError (native)
    at Test.<anonymous> (/root/node_modules/osrm/test/index.js:13:16)
    at Test.bound [as _cb] (/root/node_modules/tape/lib/test.js:61:32)
    at Test.run (/root/node_modules/tape/lib/test.js:80:10)
    at Test.bound [as run] (/root/node_modules/tape/lib/test.js:61:32)
    at Immediate.next [as _onImmediate] (/root/node_modules/tape/lib/results.js:70:15)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
npm ERR! Test failed.  See above for more details.
Makefile:90: recipe for target 'test' failed
make: *** [test] Error 1
root@routes3:~/node_modules/osrm# osrm-datastore
osrm-datastore: command not found



root@routes3:~/node_modules/osrm# npm view osrm
 
{ name: 'osrm',
  description: 'Open Source Routing Machine',
  'dist-tags': { latest: '5.2.2' },
  versions: 
   [ '0.2.2',
     '0.2.3-alpha',
     '0.2.3-alpha2',
     '0.2.3',
     '0.2.4',
     '0.2.5',
     '0.2.7',
     '0.2.8',
     '0.9.0',
     '0.9.1',
     '0.10.0',
     '0.10.1',
     '0.11.2',
     '0.12.0',
     '4.4.0-final',
     '4.5.0',
     '4.6.0',
     '4.6.1',
     '4.7.0',
     '4.7.1',
     '4.8.0',
     '4.8.1',
     '4.9.0',
     '4.9.1',
     '5.0.0',
     '5.0.1',
     '5.0.2',
     '5.1.0',
     '5.1.1',
     '5.2.1',
     '5.2.2' ],
  maintainers: 
   [ 'dennisosrm <info@project-osrm.org>',
     'jfirebaugh <john.firebaugh@gmail.com>',
     'mapbox-admin <accounts@mapbox.com>',
     'springmeyer <dane@mapbox.com>',
     'themarex <patrick@mapbox.com>',
     'willwhite <will@mapbox.com>' ],
  time: 
   { modified: '2016-06-15T17:46:56.961Z',
     created: '2014-01-16T03:34:39.878Z',
     '0.2.2': '2014-01-16T03:34:43.514Z',
     '0.2.3-alpha': '2014-01-17T02:08:14.743Z',
     '0.2.3-alpha2': '2014-01-18T04:11:08.493Z',
     '0.2.3': '2014-01-18T06:51:11.897Z',
     '0.2.4': '2014-01-24T01:03:15.929Z',
     '0.2.5': '2014-01-24T01:35:27.881Z',
     '0.2.7': '2014-01-24T04:56:33.313Z',
     '0.2.8': '2014-01-24T15:58:13.912Z',
     '0.9.0': '2014-05-01T17:46:01.384Z',
     '0.9.1': '2014-05-07T22:53:42.149Z',
     '0.10.0': '2014-05-20T20:29:45.050Z',
     '0.10.1': '2014-05-28T20:56:17.222Z',
     '0.11.2': '2014-06-27T21:55:09.524Z',
     '0.12.0': '2014-10-11T00:04:03.352Z',
     '4.4.0': '2014-10-27T19:37:28.080Z',
     '4.4.0-final': '2014-10-27T19:45:04.333Z',
     '4.5.0': '2015-01-07T09:48:01.297Z',
     '4.6.0': '2015-04-19T10:09:06.408Z',
     '4.6.1': '2015-04-22T14:20:53.044Z',
     '4.7.0': '2015-06-22T16:28:38.958Z',
     '4.7.1': '2015-08-14T23:47:48.608Z',
     '4.8.0': '2015-09-16T22:06:08.026Z',
     '4.8.1': '2015-09-20T20:56:43.689Z',
     '4.9.0-rc6': '2015-12-18T19:47:49.528Z',
     '4.9.0': '2015-12-24T11:36:33.832Z',
     '4.9.1': '2016-01-20T02:51:56.643Z',
     '5.0.0-rc.1': '2016-04-03T20:44:58.425Z',
     '5.0.0': '2016-04-22T16:07:54.572Z',
     '5.0.1': '2016-04-27T23:19:30.679Z',
     '5.0.2': '2016-04-28T10:52:00.531Z',
     '5.1.0': '2016-05-09T17:59:48.454Z',
     '5.1.1': '2016-05-20T21:21:23.754Z',
     '5.2.1': '2016-06-13T17:34:41.782Z',
     '5.2.2': '2016-06-15T17:46:56.961Z' },
  author: 'Dane Springmeyer <springmeyer>',
  repository: 
   { type: 'git',
     url: 'git://github.com/Project-OSRM/node-osrm.git' },
  readmeFilename: 'README.md',
  homepage: 'http://project-osrm.org',
  keywords: [ 'routing', 'matching', 'distance table', 'TSP' ],
  bugs: 
   { url: 'https://github.com/Project-OSRM/node-osrm/issues',
     email: 'dane@mapbox.com' },
  users: { 'joshua.marquez': true },
  license: 'BSD',
  url: 'https://github.com/Project-OSRM/node-osrm',
  version: '5.2.2',
  osrm_release: 'v5.2.2',
  main: './lib/osrm.js',
  binary: 
   { module_name: 'osrm',
     module_path: './lib/binding/',
     host: 'https://mapbox-node-binary.s3.amazonaws.com',
     remote_path: './{name}/v{version}/{configuration}/',
     package_name: '{node_abi}-{platform}-{arch}.tar.gz' },
  dependencies: { nan: '^2.1.0', 'node-pre-gyp': '~0.6.7' },
  devDependencies: 
   { 'aws-sdk': '~2.0.31',
     documentation: '^4.0.0-beta2',
     tape: '^4.2.2' },
  engines: { node: '>=4' },
  scripts: 
   { prepublish: 'npm ls',
     install: 'node-pre-gyp install --fallback-to-build',
     test: 'node test/index.js',
     docs: 'documentation build src/node_osrm.cpp --polyglot -f md -o docs/api.md' },
  gitHead: '1ecf2cb85791a148cfe205fd57ce1fe1729bd5be',
  bundleDependencies: [ 'node-pre-gyp' ],
  dist: 
   { shasum: '3d4af99c80a652924a41a71cbf86d7dc5e8ce746',
     tarball: 'https://registry.npmjs.org/osrm/-/osrm-5.2.2.tgz' },
  directories: {} }


root@routes3:~/node_modules/osrm# nodejs -v
v4.2.6

```

**Comment by MoKob** [comment]
@emiltin the process to run it from the osrm folder follows multiple steps. I am not entirely sure, but I believe you need to call:

* `make`
* potentially `npm install` (not sure here)
* `make test`

Can you try using `make` first and see if the problem persists?

**Comment by emiltin** [comment]
seems it expects a git repo for osrm-backendend?

```bash
root@routes3:~/node_modules/osrm# make
./bootstrap.sh
Success: Found pkg-config
Success: Found node

*******************
OSRM_RELEASE set to:    v5.2.2
BUILD_TYPE set to:      Release
CXX set to:             clang++
*******************


Updating to latest mason
fatal: Not a git repository (or any of the parent directories): .git
Makefile:21: recipe for target 'deps/osrm-backend-Release' failed
make: *** [deps/osrm-backend-Release] Error 128
```

**Comment by emiltin** [comment]
btw i ran 'make test' because this is what is what is mentioned in the readme: https://github.com/Project-OSRM/node-osrm#setup.

**Comment by MoKob** [comment]
I believe it expects the installed version (https://github.com/Project-OSRM/node-osrm#installing), so maybe an `npm install osrm` is really required.

**Comment by emiltin** [comment]
i started with `npm install osrm`. that created the osrm module folder where i'm running 'make test'. the osrm binaries seem to be installed in lib/bindings, so i probably don't need to build them?

```bash
root@routes3:~/node_modules/osrm# ls lib/binding/
libtbb.so.2  libtbbmalloc.so.2  libtbbmalloc_proxy.so.2  lua  osrm-contract  osrm-datastore  osrm-extract  osrm-routed  osrm.node
root@routes3:~/node_modules/osrm# lib/binding/osrm-extract -v
[info] v5.2.0
root@routes3:~/node_modules/osrm# lib/binding/osrm-extract --help
[info] osrm-extract <input.osm/.osm.bz2/.osm.pbf> [options]:

Options:
  -v [ --version ]                      Show version
  -h [ --help ]                         Show this help message

Configuration:
  -p [ --profile ] arg (="profile.lua") Path to LUA routing profile
  -t [ --threads ] arg (=1)             Number of threads to use
  --generate-edge-lookup [=arg(=1)] (=0)
                                        Generate a lookup table for internal 
                                        edge-expanded-edge IDs to OSM node 
                                        pairs
  --small-component-size arg (=1000)    Number of nodes required before a 
                                        strongly-connected-componennt is 
                                        considered big (affects nearest 
                                        neighbor snapping)
```

**Comment by MoKob** [comment]
@emiltin ok. Seems like someone with a bit more understanding of how it's supposed to work is needed (cc @TheMarex)

I follow the following steps to have it build/test locally:

`git clone *node-osrm*`

In the node-osrm folder:
* `make`
* `make test`

To make sure that the osrm-files align, you might need to delete all osrm files in the folder.

This results in:
```
ok 182 null
ok 183 should be equal
ok 184 should be equal
ok 185 (unnamed assert)
# nearest: can ask for multiple nearest pts
ok 186 null
ok 187 should be equal
# nearest: throws on invalid args
ok 188 should throw
ok 189 should throw
ok 190 should throw
ok 191 should throw
ok 192 should throw
ok 193 should throw

1..193
# tests 193
# pass  193

# ok
```

**Comment by emiltin** [comment]
thanks. i didn't use git to checkout the, but instead suggested in the readme 'npm install osrm'

**Comment by daniel-j-h** [comment]
Closing as resolved.

**Comment by gustavobk** [comment]
Just fyi, I did exactly the same as emiltin. Perhaps the documentation isn't that clear about the steps necessary for testing.
